language: java

jdk: oraclejdk8

env:
- MAVEN_VERSION=3.3.9

install:
  - "docker-compose build"
script: "docker-compose run specs"

cache:
  directories:
  - $HOME/.m2

before_install:
- "docker-compose up -d"

services:
- docker

after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh success $WEBHOOK_URL

after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK_URL