# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: powerfour
      POSTGRES_DB: powerfour
      POSTGRES_USER: powerfour
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data

  specs:
    build:
      context: .
      dockerfile: Dockerfile
    command: mvn clean install
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/powerfour

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080