# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: powerfour
      POSTGRES_DB: powerfour
      POSTGRES_USER: powerfour
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080