# Use postgres/example user/password credentials
version: '3.1'

services:

  database:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: powerfour
      POSTGRES_DB: powerfour
      POSTGRES_USER: powerfour
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: mvn spring-boot:run
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/powerfour

  specs:
    build:
      context: .
      dockerfile: Dockerfile
    command: mvn clean install
    depends_on:
    - database
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/powerfour

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080